image: docker:stable

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - deploy

frontend:
  stage: build
  script:
    - docker build --target frontend -t ${CI_REGISTRY_IMAGE}:frontend-${CI_COMMIT_REF_SLUG} .
    - docker push ${CI_REGISTRY_IMAGE}:frontend-${CI_COMMIT_REF_SLUG}

backend:
  allow_failure: true
  stage: build
  script:
    - docker build --target backend -t ${CI_REGISTRY_IMAGE}:backend-${CI_COMMIT_REF_SLUG} .
    - docker push ${CI_REGISTRY_IMAGE}:backend-${CI_COMMIT_REF_SLUG}

.named_deployment: &named_deployment
  stage: deploy
  when: manual
  script:
    - docker stack deploy -c stack.yml --with-registry-auth $APP_NAME
  only:
    - main

demo:
  variables:
    APP_NAME: monorepo-demo
    PERSIST_VOLUME: "true"
    HOST_URL: https://demo.v2.openpra.org
  <<: *named_deployment

staging:
  variables:
    APP_NAME: monorepo-staging
    PERSIST_VOLUME: "true"
    HOST_URL: https://staging.v2.openpra.org
  <<: *named_deployment

production:
  variables:
    APP_NAME: monorepo-production
    PERSIST_VOLUME: "true"
    HOST_URL: https://v2.openpra.org
  <<: *named_deployment


.review_set_vars: &review_set_vars
  - export APP_NAME=$(echo "monorepo-$CI_COMMIT_REF_SLUG" | cut -c 1-40)
  - export TRUNCATED_SLUG=$(echo "$CI_COMMIT_REF_SLUG" | cut -c 1-40)
  - export HOST_URL=$(echo "review-$TRUNCATED_SLUG.$DOMAIN")
  - export HTTPS_HOST_URL=$(echo "https://$HOST_URL")
  - export API_ENDPOINT=$(echo "$HTTPS_HOST_URL/api")
  - echo $APP_NAME
  - echo $TRUNCATED_SLUG
  - echo $HOST_URL
  - echo $HTTPS_HOST_URL
  - echo $API_ENDPOINT

review:
  stage: deploy
  variables:
    DOMAIN: v2.openpra.org
    PERSIST_VOLUME: "false"
  script:
    - *review_set_vars
    - docker stack deploy -c stack.yml --with-registry-auth $APP_NAME
  except:
    - main

