version: '3.6'

volumes:
  data_db:

services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - data_db:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8082:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
