version: '3.3'

services:
  nestjs_backend:
    restart: always
    env_file:
      - .env
    expose:
      - "3000"
    depends_on:
      - backend

  backend:
    environment:
      - SECRET_KEY
    env_file:
      - variables.env
    depends_on:
      - db
      - mongodb

  db:
    image: postgres:10.5
    restart: always
    expose:
      - "5432"
    env_file:
      - variables.env

  mongodb:
    restart: always
    image: mongo:5
    expose:
      - "27017"